### ISSUE TITLE
OFX import missing

### ISSUE THREAD

**Issue by TraceyC77** [flathub/org.gnucash.GnuCash#11]
Under File - Import there should be an option for OFX/QFX Import. It is not in the menu. It needs to be compiled with ofx support for this selection to be present.

I understand from #9 that you are working on publishing 3.0 and are working through compile errors. I would like to also request a build of 2.6.21 since 3.0 has some severe reported bugs which aren't yet worked out. Please add OFX import support in either case. Thank you.

Also, just noting that the page for GnuCash doesn't show its version or update date.
https://flathub.org/apps/details/org.gnucash.GnuCash

**Comment by nedrichards** [comment]
ofx support should be in the PR for #9 - although that's still blocked.

**Comment by gjanssens** [comment]
As far as I can see OFX/QFX import is now in the menus in the just pushed flatpak for version 3.6.
