### ISSUE TITLE
Bug URL changed to bugs.gnucash.org

### ISSUE THREAD

**Issue by fellen** [flathub/org.gnucash.GnuCash#15]
Hi,

because gnome.org had announced to close bugzilla.gnome.org, we have set up our own bugzilla instance at https://bugs.gnucash.org.
Can you adjust your links, please?

Sojurces:
https://lists.gnucash.org/pipermail/gnucash-announce/2018-June/000284.html
https://lists.gnucash.org/pipermail/gnucash-announce/2018-June/000285.html

**Comment by TingPing** [comment]
The upstream appdata file is used, so this is something to change there.

**Comment by barthalion** [comment]
On similar note, @fellen, would anyone from upstream team be interested in helping with maintenance or at least getting write access just in case?

**Comment by fellen** [comment]
>   The upstream appdata file is used, so this is something to change there.

Right, we missed a few instances. Should be fixed in https://github.com/Gnucash/gnucash/commit/756f444ac37861bad35e9ecd9b505a8d525b95f6. If not, let me know it.

>   would anyone from upstream team be interested in helping with maintenance or at least getting write access just in case?

Sorry, I fear we have not the man power in the core team. But you might ask on <gnucash-devel@gnucash.org>.

**Comment by fellen** [comment]
> On similar note, @fellen, would anyone from upstream team be interested in helping with maintenance or at least getting write access just in case?

You  should ask our flatpack expert @gjanssens.

**Comment by gjanssens** [comment]
While I don't have much time available I'm fine with getting write access. I'll see how much I can help out in the coming months (unfortunately not much right now).
