### ISSUE TITLE
Finance::Quote

### ISSUE THREAD

**Issue by ramcq** [flathub/org.gnucash.GnuCash#19]
Is there any plan to include Finance::Quote in the GnuCash Flatpak? Users of EndlessOS are requesting it: https://community.endlessos.com/t/gnucash-finance-quote-not-installed-properly/8356

**Comment by wjt** [comment]
Our user reports that this is now working for them https://community.endlessos.com/t/finance-quote-is-working-now-on-gnucash-version-flathub-3-8-7/11723

**Comment by wjt** [comment]
@gjanssens presumably 02d77fca4c00fcb10735952aea7359cd16436bb2 is the relevant change.

**Comment by gjanssens** [comment]
Right I should have mentioned it in this issue. I have indeed implemented Finance::Quote support in the latest flathub gnucash package.

@wjt Thanks for reporting it works now!
