### ISSUE TITLE
GnuCash does not open

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnucash.GnuCash#2]
![captura de tela de 2017-11-24 21-29-45](https://user-images.githubusercontent.com/26097419/33225441-a02d4286-d15e-11e7-8863-3236baab09ad.png)

**Comment by LeandroStanger** [comment]
@nedrichards Could help
[eos-diagnostic-171124_221943_UTC-0200.txt](https://github.com/flathub/org.gnucash.GnuCash/files/1502703/eos-diagnostic-171124_221943_UTC-0200.txt)

**Comment by nedrichards** [comment]
Well, it looks like your dump is very similar to [someone else's problem](https://lists.gnucash.org/pipermail/gnucash-user/2017-August/071798.html). I can't reproduce it myself, which is strange. You're in the pt-BR locale?

**Comment by LeandroStanger** [comment]
@nedrichards  Yes

**Comment by LeandroStanger** [comment]
@nedrichards If you upgrade to version 2.6.18

**Comment by nedrichards** [comment]
That's a good idea - just testing the upgrade right now.

**Comment by nedrichards** [comment]
2.6.18 update is on https://github.com/flathub/org.gnucash.GnuCash/pull/3

**Comment by LeandroStanger** [comment]
@nedrichards did not work

**Comment by nedrichards** [comment]
Hrm, I'm unable to reproduce this when switching to pt-BR on my endless machine, will keep thinking.

**Comment by LeandroStanger** [comment]
@nedrichards 
[eos-diagnostic-171201_213328_UTC-0200.txt](https://github.com/flathub/org.gnucash.GnuCash/files/1523285/eos-diagnostic-171201_213328_UTC-0200.txt)
leandro@leandro-stanger:~$ flatpak run org.gnucash.GnuCash
;;; note: source file /app/share/guile/2.0/ice-9/deprecated.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/deprecated.go
;;; note: source file /app/share/guile/2.0/ice-9/eval-string.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/eval-string.go
;;; found fresh local cache at /sysroot/home/leandro/.var/app/org.gnucash.GnuCash/cache/guile/ccache/2.0-LE-8-2.0/app/share/guile/2.0/ice-9/eval-string.scm.go
;;; note: source file /app/share/guile/2.0/system/base/message.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/base/message.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /app/share/guile/2.0/system/base/message.scm
;;; it seems /app/share/guile/2.0/system/base/message.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/srfi/srfi-9.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/srfi/srfi-9.go
;;; compiling /app/share/guile/2.0/srfi/srfi-9.scm
;;; it seems /app/share/guile/2.0/srfi/srfi-9.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/system/base/ck.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/base/ck.go
;;; compiling /app/share/guile/2.0/system/base/ck.scm
;;; it seems /app/share/guile/2.0/system/base/ck.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/ice-9/match.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/match.go
;;; compiling /app/share/guile/2.0/ice-9/match.scm
;;; it seems /app/share/guile/2.0/ice-9/match.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/ice-9/optargs.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/optargs.go
;;; compiling /app/share/guile/2.0/ice-9/optargs.scm
;;; it seems /app/share/guile/2.0/ice-9/optargs.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/system/base/pmatch.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/base/pmatch.go
;;; compiling /app/share/guile/2.0/system/base/pmatch.scm
;;; it seems /app/share/guile/2.0/system/base/pmatch.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/ice-9/receive.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/receive.go
;;; compiling /app/share/guile/2.0/ice-9/receive.scm
;;; it seems /app/share/guile/2.0/ice-9/receive.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/system/vm/program.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/vm/program.go
;;; compiling /app/share/guile/2.0/system/vm/program.scm
;;; note: source file /app/share/guile/2.0/system/foreign.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/foreign.go
;;; compiling /app/share/guile/2.0/system/foreign.scm
;;; WARNING: compilation of /app/share/guile/2.0/system/foreign.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/srfi/srfi-9/gnu.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/srfi/srfi-9/gnu.go
;;; compiling /app/share/guile/2.0/srfi/srfi-9/gnu.scm
;;; WARNING: compilation of /app/share/guile/2.0/srfi/srfi-9/gnu.scm failed:
;;; ERROR: no such language objcode
;;; WARNING: compilation of /app/share/guile/2.0/system/vm/program.scm failed:
;;; ERROR: no code for module (system vm program)
;;; note: source file /app/share/guile/2.0/srfi/srfi-26.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/srfi/srfi-26.go
;;; compiling /app/share/guile/2.0/srfi/srfi-26.scm
;;; WARNING: compilation of /app/share/guile/2.0/srfi/srfi-26.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/language/tree-il.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/language/tree-il.go
;;; compiling /app/share/guile/2.0/language/tree-il.scm
;;; WARNING: compilation of /app/share/guile/2.0/language/tree-il.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/srfi/srfi-11.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/srfi/srfi-11.go
;;; compiling /app/share/guile/2.0/srfi/srfi-11.scm
;;; WARNING: compilation of /app/share/guile/2.0/srfi/srfi-11.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/language/scheme/decompile-tree-il.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/language/scheme/decompile-tree-il.go
;;; compiling /app/share/guile/2.0/language/scheme/decompile-tree-il.scm
;;; WARNING: compilation of /app/share/guile/2.0/language/scheme/decompile-tree-il.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/ice-9/vlist.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/vlist.go
;;; compiling /app/share/guile/2.0/ice-9/vlist.scm
;;; WARNING: compilation of /app/share/guile/2.0/ice-9/vlist.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/language/tree-il/primitives.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/language/tree-il/primitives.go
;;; compiling /app/share/guile/2.0/language/tree-il/primitives.scm
;;; WARNING: compilation of /app/share/guile/2.0/language/tree-il/primitives.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/language/glil.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/language/glil.go
;;; compiling /app/share/guile/2.0/language/glil.scm
;;; WARNING: compilation of /app/share/guile/2.0/language/glil.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/ice-9/control.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/control.go
;;; compiling /app/share/guile/2.0/ice-9/control.scm
;;; WARNING: compilation of /app/share/guile/2.0/ice-9/control.scm failed:
;;; ERROR: no such language objcode
Backtrace:
In ice-9/boot-9.scm:
2412: 19 [save-module-excursion #<procedure 2931b40 at ice-9/boot-9.scm:3102:17 ()>]
3121: 18 [#<procedure 2931b40 at ice-9/boot-9.scm:3102:17 ()>]
In unknown file:
   ?: 17 [primitive-load-path "ice-9/control" ...]
In ice-9/eval.scm:
 505: 16 [#<procedure 1c3f480 at ice-9/eval.scm:499:4 (exp)> (define-module # # ...)]
In ice-9/psyntax.scm:
1107: 15 [expand-top-sequence ((define-module # # # ...)) () ((top)) ...]
 988: 14 [scan ((define-module (ice-9 control) #:re-export ...)) () ...]
1214: 13 [syntax-type (define-module (ice-9 control) #:re-export ...) () ...]
1423: 12 [expand-macro #<procedure 1cdcce0 at ice-9/boot-9.scm:3512:2 (x)> # () ...]
In ice-9/boot-9.scm:
3601: 11 [#<procedure 29310c0 (name name* arg)> #(syntax-object ice-9 # ...) (#) ...]
3534: 10 [parse (# # # #) () () ...]
In ice-9/psyntax.scm:
2805: 9 [match* #:re-export #(atom #:use-module) ...]
In oop/goops/dispatch.scm:
 207: 8 [#<procedure 20887e0 at oop/goops/dispatch.scm:203:4 args> # #]
In system/base/target.scm:
  59: 7 [with-target "x86_64-unknown-linux-gnu" ...]
In oop/goops/dispatch.scm:
 185: 6 [#<procedure 294bc60 at oop/goops/dispatch.scm:184:6 ()>]
In system/base/compile.scm:
 254: 5 [compile (lambda (p259 c258 p257 ...) (case-lambda # #)) #:from ...]
 175: 4 [compile-passes scheme value (#:partial-eval? #f #:cse? #f)]
In system/base/language.scm:
  92: 3 [lookup-compilation-order scheme value]
In ice-9/boot-9.scm:
 336: 2 [or-map #<procedure 294bc00 at system/base/language.scm:85:21 (pair)> (#)]
In system/base/language.scm:
  82: 1 [lp tree-il ((# . #<procedure compile-tree-il (x e opts)>))]
In unknown file:
   ?: 0 [scm-error misc-error #f "~A ~S" ("no such language" tree-il) #f]

ERROR: In procedure scm-error:
ERROR: no such language tree-il
leandro@leandro-stanger:~$ eos-diagnostics
Endless OS Diagnostics file saved as:
/sysroot/home/leandro/eos-diagnostic-171201_213328_UTC-0200.txt
Please send that file (not this message!) to the Endless Community or Support.

**Comment by LeandroStanger** [comment]
Endless OS 3.3.6

;;; note: source file /app/share/guile/2.0/ice-9/deprecated.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/deprecated.go
;;; note: source file /app/share/guile/2.0/ice-9/eval-string.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/eval-string.go
;;; found fresh local cache at /sysroot/home/leandro/.var/app/org.gnucash.GnuCash/cache/guile/ccache/2.0-LE-8-2.0/app/share/guile/2.0/ice-9/eval-string.scm.go
;;; note: source file /app/share/guile/2.0/system/base/message.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/base/message.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /app/share/guile/2.0/system/base/message.scm
;;; it seems /app/share/guile/2.0/system/base/message.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/srfi/srfi-9.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/srfi/srfi-9.go
;;; compiling /app/share/guile/2.0/srfi/srfi-9.scm
;;; it seems /app/share/guile/2.0/srfi/srfi-9.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/system/base/ck.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/base/ck.go
;;; compiling /app/share/guile/2.0/system/base/ck.scm
;;; it seems /app/share/guile/2.0/system/base/ck.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/ice-9/match.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/match.go
;;; compiling /app/share/guile/2.0/ice-9/match.scm
;;; it seems /app/share/guile/2.0/ice-9/match.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/ice-9/optargs.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/optargs.go
;;; compiling /app/share/guile/2.0/ice-9/optargs.scm
;;; it seems /app/share/guile/2.0/ice-9/optargs.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/system/base/pmatch.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/base/pmatch.go
;;; compiling /app/share/guile/2.0/system/base/pmatch.scm
;;; it seems /app/share/guile/2.0/system/base/pmatch.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/ice-9/receive.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/receive.go
;;; compiling /app/share/guile/2.0/ice-9/receive.scm
;;; it seems /app/share/guile/2.0/ice-9/receive.scm
;;; is part of the compiler; skipping auto-compilation
;;; note: source file /app/share/guile/2.0/system/vm/program.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/vm/program.go
;;; compiling /app/share/guile/2.0/system/vm/program.scm
;;; note: source file /app/share/guile/2.0/system/foreign.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/system/foreign.go
;;; compiling /app/share/guile/2.0/system/foreign.scm
;;; WARNING: compilation of /app/share/guile/2.0/system/foreign.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/srfi/srfi-9/gnu.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/srfi/srfi-9/gnu.go
;;; compiling /app/share/guile/2.0/srfi/srfi-9/gnu.scm
;;; WARNING: compilation of /app/share/guile/2.0/srfi/srfi-9/gnu.scm failed:
;;; ERROR: no such language objcode
;;; WARNING: compilation of /app/share/guile/2.0/system/vm/program.scm failed:
;;; ERROR: no code for module (system vm program)
;;; note: source file /app/share/guile/2.0/srfi/srfi-26.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/srfi/srfi-26.go
;;; compiling /app/share/guile/2.0/srfi/srfi-26.scm
;;; WARNING: compilation of /app/share/guile/2.0/srfi/srfi-26.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/language/tree-il.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/language/tree-il.go
;;; compiling /app/share/guile/2.0/language/tree-il.scm
;;; WARNING: compilation of /app/share/guile/2.0/language/tree-il.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/srfi/srfi-11.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/srfi/srfi-11.go
;;; compiling /app/share/guile/2.0/srfi/srfi-11.scm
;;; WARNING: compilation of /app/share/guile/2.0/srfi/srfi-11.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/language/scheme/decompile-tree-il.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/language/scheme/decompile-tree-il.go
;;; compiling /app/share/guile/2.0/language/scheme/decompile-tree-il.scm
;;; WARNING: compilation of /app/share/guile/2.0/language/scheme/decompile-tree-il.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/ice-9/vlist.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/vlist.go
;;; compiling /app/share/guile/2.0/ice-9/vlist.scm
;;; WARNING: compilation of /app/share/guile/2.0/ice-9/vlist.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/language/tree-il/primitives.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/language/tree-il/primitives.go
;;; compiling /app/share/guile/2.0/language/tree-il/primitives.scm
;;; WARNING: compilation of /app/share/guile/2.0/language/tree-il/primitives.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/language/glil.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/language/glil.go
;;; compiling /app/share/guile/2.0/language/glil.scm
;;; WARNING: compilation of /app/share/guile/2.0/language/glil.scm failed:
;;; ERROR: no such language objcode
;;; note: source file /app/share/guile/2.0/ice-9/control.scm
;;;       newer than compiled /app/lib/guile/2.0/ccache/ice-9/control.go
;;; compiling /app/share/guile/2.0/ice-9/control.scm
;;; WARNING: compilation of /app/share/guile/2.0/ice-9/control.scm failed:
;;; ERROR: no such language objcode
Backtrace:
In ice-9/boot-9.scm:
2412: 19 [save-module-excursion #<procedure 2dea720 at ice-9/boot-9.scm:3102:17 ()>]
3121: 18 [#<procedure 2dea720 at ice-9/boot-9.scm:3102:17 ()>]
In unknown file:
   ?: 17 [primitive-load-path "ice-9/control" ...]
In ice-9/eval.scm:
 505: 16 [#<procedure 1eca480 at ice-9/eval.scm:499:4 (exp)> (define-module # # ...)]
In ice-9/psyntax.scm:
1107: 15 [expand-top-sequence ((define-module # # # ...)) () ((top)) ...]
 988: 14 [scan ((define-module (ice-9 control) #:re-export ...)) () ...]
1214: 13 [syntax-type (define-module (ice-9 control) #:re-export ...) () ...]
1423: 12 [expand-macro #<procedure 1f669c0 at ice-9/boot-9.scm:3512:2 (x)> # () ...]
In ice-9/boot-9.scm:
3601: 11 [#<procedure 2f07c00 (name name* arg)> #(syntax-object ice-9 # ...) (#) ...]
3534: 10 [parse (# # # #) () () ...]
In ice-9/psyntax.scm:
2805: 9 [match* #:re-export #(atom #:use-module) ...]
In oop/goops/dispatch.scm:
 207: 8 [#<procedure 2e0fe70 at oop/goops/dispatch.scm:203:4 args> # #]
In system/base/target.scm:
  59: 7 [with-target "x86_64-unknown-linux-gnu" ...]
In oop/goops/dispatch.scm:
 185: 6 [#<procedure 2f078d0 at oop/goops/dispatch.scm:184:6 ()>]
In system/base/compile.scm:
 254: 5 [compile (lambda (p259 c258 p257 ...) (case-lambda # #)) #:from ...]
 175: 4 [compile-passes scheme value (#:partial-eval? #f #:cse? #f)]
In system/base/language.scm:
  92: 3 [lookup-compilation-order scheme value]
In ice-9/boot-9.scm:
 336: 2 [or-map #<procedure 2f07870 at system/base/language.scm:85:21 (pair)> (#)]
In system/base/language.scm:
  82: 1 [lp tree-il ((# . #<procedure compile-tree-il (x e opts)>))]
In unknown file:
   ?: 0 [scm-error misc-error #f "~A ~S" ("no such language" tree-il) #f]

ERROR: In procedure scm-error:
ERROR: no such language tree-il

**Comment by LeandroStanger** [comment]
@nedrichards If you upgrade to version 2.6.19?

**Comment by gjanssens** [comment]
It's not normal that guile starts recompiling all of its own scm files so something weird seems to be going on there. It may be either a different version of guile is found on your system (guile 2.0?) or guile's load-compiled-path is incorrect somehow.
Do you have the same problems with the 3.x flatpak ?

**Comment by gjanssens** [comment]
See also #24
