### ISSUE TITLE
component type="generic" in appstream.xml

### ISSUE THREAD

**Issue by jgarciao** [flathub/org.gnucash.GnuCash#29]
I was checking flatpak's appstream.xml file and found that this applications has `component type="generic"`. 

I think if should be `component type="desktop"` or `component type="desktop-application"`

It if was a new application this bug would prevent this application from being listed in the website. Maybe this bug was introduced in an update

**Comment by jgarciao** [comment]
Thanks for fixing it. Now the app info (version, update date, ...) is properly updated in the website
https://flathub.org/apps/details/org.gnucash.GnuCash

**Comment by gjanssens** [comment]
Indeed, thanks for spotting this!
