### ISSUE TITLE
Build fails at aqbanking module due to broken source url

### ISSUE THREAD

**Issue by cjao** [flathub/org.gnucash.GnuCash#31]
I recently tried building gnucash to debug some crashes. The build failed at the aqbanking module because the url for the source is no longer valid. Please update either source url (see https://www.aquamaniac.de/rdm/projects/aqbanking/files) or the version of aqbanking altogether.

**Comment by gjanssens** [comment]
Hi, I have changed the module to use the most recent version of aqbanking (6.1.4). The build ran successfully, the new flatpak will be pushed to the flathub repo automatically within a few hours.
