### ISSUE TITLE
Remove dconf workaround

### ISSUE THREAD

**Issue by eszlari** [flathub/org.gnucash.GnuCash#36]
https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

**Comment by gjanssens** [comment]
This is blocked by flatpak/flatpak#4333 and/or flatpak/flatpak#4209

**Comment by gjanssens** [comment]
We have worked around the flatpak issues and have removed dconf workaround in gnucash 4.7.
