### ISSUE TITLE
AqBanking assisant for HBCI don't work

### ISSUE THREAD

**Issue by BaumiCoder** [flathub/org.gnucash.GnuCash#37]
I have installed GnuCash from flathub on my Linux Mint 18.3 Sylvia 64-bit (MATE 1.18.0) system. I tried to setup a HBCI connection to my bankaccount. I go to tools ("Werkzeuge") - Set up online banking ("Online Banking einrichten") and click continue. Then a button "Start AqBanking setup wizard" ("AqBanking Einrichtungs-Assistenten starten") appears. I click on this button and nothing happens. (The text in the brackets are the original string in my german installation.)

if I start GnuCash with the shell I get this out put, when doing the steps above:
```
flatpak run org.gnucash.GnuCash --logto stdout
Finance::Quote Version 1.49 wurde gefunden.
* 13:29:02 ERROR <gnc.import.aqbanking> gnc_AB_BANKING_new: assertion 'AB_Banking_Init(api) == 0' failed
* 13:29:09 ERROR <gnc.import.aqbanking> aai_wizard_page_prepare: assertion 'info->api' failed
* 13:29:13 ERROR <gnc.import.aqbanking> aai_wizard_button_clicked_cb: assertion 'banking' failed
```
It looks like something of AqBanking is missing, but I don't find a package for this on flathub. I have installed the "Aqbanking-tools" package from the native Linux Mint repo, but the problem still appears.

I think there is a bug in the flathub package, isn't it?

**Comment by fellen** [comment]
> It looks like something of AqBanking is missing, but I don't find a package for this on flathub. I have installed the "Aqbanking-tools" package from the native Linux Mint repo, but the problem still appears.

No, the bundle contains the aqbanking and gwenhyfar packages.

- Which versions are you currently using? See https://wiki.gnucash.org/wiki/De/Feedback#Verwendete_Versionen or https://wiki.gnucash.org/wiki/AqBanking#Determinating_the_Versions

**Comment by BaumiCoder** [comment]
This are outputs of the version commands on my system:

```
flatpak run --command=sh org.gnucash.GnuCash
sh-5.0$ gnucash --version
GnuCash 4.2
Build ID: Flathub 4.2
sh-5.0$ aqbanking-cli versions
Versions:
 AqBanking-CLI: 6.2.1
 Gwenhywfar   : 5.3.0.0
 AqBanking    : 6.2.1.0
```

**Comment by fellen** [comment]
Short after our last release have been several updates on the aqbanking project.
Can you test one of our [nightlies](https://code.gnucash.org/builds/flatpak/maint/?C=M;O=D) >= 2020-10-16?

**Comment by BaumiCoder** [comment]
I uninstalled the normal version and installed the latest nightly build.
`sudo flatpak install gnucash-maint-C4.2-123-gafcf1765f-D4.2.flatpakref`
The error still appears. The log output looks quietly the same.
```
(flatpak run org.gnucash.GnuCash --logto stdout
Diese Version befindet sich noch in Entwicklung.
Sie kann funktionieren, muss aber nicht. 
Fehler und andere Probleme werden auf gnucash-devel@gnucash.org diskutiert.
Fehlerberichte können hier eingesehen und erstellt werden: https://bugs.gnucash.org
Um die letzte stabile Version zu finden, sehen Sie bitte hier nach: https://www.gnucash.org/
Finance::Quote Version 1.49 wurde gefunden.
* 11:22:38 ERROR <gnc.import.aqbanking> gnc_AB_BANKING_new: assertion 'AB_Banking_Init(api) == 0' failed
* 11:22:39 ERROR <gnc.import.aqbanking> aai_wizard_page_prepare: assertion 'info->api' failed
* 11:22:40 ERROR <gnc.import.aqbanking> aai_wizard_button_clicked_cb: assertion 'banking' failed)
```
The version commands output:
```
flatpak run --command=sh org.gnucash.GnuCash
sh-5.0$ gnucash --version
GnuCash 4.2 development version
Build ID: git 4.2-123-gafcf1765f+(2020-11-05)
sh-5.0$ aqbanking-cli versions
Versions:
 AqBanking-CLI: 6.2.5
 Gwenhywfar   : 5.4.1.0
 AqBanking    : 6.2.5.0
```

**Comment by fellen** [comment]
Ich bekomme dann den Dialog "Aqbanking-Einrichtung" mit den beiden Reitern: Benutzer, Konten.

Kann es sein, daß das entsprechende Fenster von einem anderen verdeckt wird oder auf einem anderen, möglicherweise nich eingestöpselten Monitor dargestellt wird?

**Comment by BaumiCoder** [comment]
Thank you for your adivce. Now I have cleared the .aqbanking folder on my system and it works.
```
flatpak run org.gnucash.GnuCash --logto stdout
Diese Version befindet sich noch in Entwicklung.
Sie kann funktionieren, muss aber nicht. 
Fehler und andere Probleme werden auf gnucash-devel@gnucash.org diskutiert.
Fehlerberichte können hier eingesehen und erstellt werden: https://bugs.gnucash.org
Um die letzte stabile Version zu finden, sehen Sie bitte hier nach: https://www.gnucash.org/
Finance::Quote Version 1.49 wurde gefunden.
* 10:29:23 ERROR <aqbanking> banking_update.c:  610: No AqBanking config folder found at [/home/michael/.aqbanking/settings6/users] (-1)
* 10:29:23 ERROR <aqbanking> banking_update.c:  610: No AqBanking config folder found at [/home/michael/.aqbanking/settings/users] (-1)
* 10:29:23 ERROR <aqbanking> banking_update.c:  411: There is no old settings folder, need initial setup
* 10:29:41 ERROR <gwenhywfar> pathmanager.c:   83: Path "aqhbci/xmldatadir" already exists
```
