### ISSUE TITLE
Importing aqConfig profiles

### ISSUE THREAD

**Issue by marksarnold** [flathub/org.gnucash.GnuCash#41]
Hello,
I have been using GnuCash 3.x from the LinuxMint repo and just installed the 4.5 flatpak version.
Is there a way to migrate my old online banking settings, so I dont have to set up everything from scratch?

The old version stored everything in ~/.aqbanking , but the flatpak distro isnt picking it up from there.
I assume I have to copy it somewhere into the flatpak installation folder structure?

Thanks,
Mark

**Comment by jralls** [comment]
According to [flatpak#1215](https://github.com/flatpak/flatpak/issues/1214) it would be ~/.var/app/org.gnucash.Gnucash/aqbanking. Please use the GnuCash [mailing list](https://lists.gnucash.org/mailman/listinfo/gnucash-user) for future support questions.
