### ISSUE TITLE
Update runtime to v41

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnucash.GnuCash#44]

**Comment by travier** [comment]
This is now fixed (see https://github.com/flathub/org.gnucash.GnuCash/pull/48).

**Comment by picsel2** [comment]
Nice! But unfortunately the build of the master branch fails currently and build bot [does not provide any useful output](https://flathub.org/builds/#/builders/8/builds/8647).

**Comment by hfiguiere** [comment]
Unfortunately the build has been purge (too old). I just retriggered a new one. And if it fails, I can have a further look at what the problem is.


(sadly nobody gets notified when a build fail outside of a PR)

**Comment by jralls** [comment]
A missing close-quote on the GNUCASH_BUILD_ID. Fixed and a new build is running. Thanks for the heads-up.
