### ISSUE TITLE
Update Finance::Quote

### ISSUE THREAD

**Issue by taaem** [flathub/org.gnucash.GnuCash#51]
Hello,
`Finance::Quote` is at version v1.49 in the flatpak but upstream is already at v1.51, which fixes a lot of online sources.
Best Regards

**Comment by fellen** [comment]
Yes, I know. I had started the task some time ago, but it is time consuming to update the whole dependcy tree in [modules/finance-quote-sources.json](https://github.com/Gnucash/gnucash-on-flatpak/blob/master/modules/finance-quote-sources.json) and I got distracted by other errands.

If you have some time,can you create a pull request?

**Comment by gjanssens** [comment]
This has been fixed for GnuCash package 4.12-1. That one ships with Finance::Quote version 1.53.
