### ISSUE TITLE
Update to runtime v42

### ISSUE THREAD

**Issue by Altonss** [flathub/org.gnucash.GnuCash#55]
Runtime v41 has reached end of life since September 17...

**Comment by jralls** [comment]
This is a dependent repo, the real work happens [here](https://github.com/gnucash/gnucash-on-flatpak/). Please use that repo for future issues.

We've updated that repo to Gnome runtime 43.

**Comment by fellen** [comment]
We got also [Bug 798635](https://bugs.gnucash.org/show_bug.cgi?id=798635) - Bump org.gnome.Platform runtime to 43

**Comment by gjanssens** [comment]
I have seen it. We're working on this.

**Comment by jralls** [comment]
Note that we've released on `flathub` GnuCash 4.12-2 with Gnome runtime v42. GnuCash 4.13, which will be released in December, will have runtime v43, and the [nightlies](https://code.gnucash.org/builds/flatpak/maint) have had v43 since October 20.
