### ISSUE TITLE
Please update Finance::Quote

### ISSUE THREAD

**Issue by bedaro** [flathub/org.gnucash.GnuCash#60]
It looks like the latest stable version uses Finance::Quote 1.49. This version is pretty old; 1.53 was released a few weeks ago and contains some important compatibility fixes, like for the TSP website (https://github.com/finance-quote/finance-quote/issues/209).

**Comment by jralls** [comment]
Geert did so [two weeks ago](https://github.com/flathub/org.gnucash.GnuCash/commit/15a3c3f42f53910006eab13a09b28b3ed5e3dd6b), and it should be what you get if you run `flatpak update`. If not please run `flatpak info gnucash`; the reported version should be 4.12-2.

**Comment by bedaro** [comment]
Yes I see that update now, thanks
