### ISSUE TITLE
fq not included in Flatpak?

### ISSUE THREAD

**Issue by wind77** [flathub/org.gnucash.GnuCash#62]
Hi.
I just downloaded the Flatpak version of GNUCash, and was setting up the auto update quote feature.
However, following the instruction on [GNUCash](https://www.gnucash.org/docs/v4/C/gnucash-help/finance-quote-install.html#ftn.idm17086) , it seems that Finance::Quote module was missing.
When I followed Procedure 11.4, the sudo command `gnc-fq-check` actually directed me to download the GNUCash again, from the AUR repo.
It puzzles me that in order to use fq, the Flatpak version redirected me to install an AUR version of GNUCash.
Is there any workaround without installing multiple version of GNUCash?

**Comment by jralls** [comment]
You didn't run `gnc-fq-check` in the flatpak, you tried to run it from the OS's command line. Arch Linux recognized the command as being uninstalled and associated with GnuCash so it told you to install GnuCash.  To run things in the flatpak use `flatpak run --command=sh org.gnucash.GnuCash` to get a shell prompt inside the flatpak from which you can run `gnc-fq-check`. Note that `gnc-fq-update` doesn't work in the flatpak: You're stuck with whatever version of Finance::Quote was built in the flatpak.

You'll find more information about using GnuCash in a flatpak in the [GnuCash Wiki](https://wiki.gnucash.org/wiki/Flatpak).

Note also that bug trackers are for reporting bugs, not for asking support questions. We have [mailing lists](https://wiki.gnucash.org/wiki/Mailing_Lists) and an [IRC channel](https://wiki.gnucash.org/wiki/IRC) for that.

**Comment by wind77** [comment]
@jralls 
Appreciate your help!
Thanks!
