### ISSUE TITLE
Version Information in new Flatpak Release?

### ISSUE THREAD

**Issue by rsbrux** [flathub/org.gnucash.GnuCash#68]
For many months now I have been using GC 4.13+ installed as a flatpak under Ubuntu Studio 22.04 LTS.
Today KDE Discover offered to update GC "to version 4.13+ (Flathub 4.13) (stable)"
However, looking at the Flathub web page (https://flathub.org/apps/details/org.gnucash.GnuCash), I see:
Updated: March 25, 2023
Version: 4.14+ (Flathub 4.14)

After letting Discover perform the update, running:
flatpak run --command=sh org.gnucash.GnuCash
gnucash --version
as described here: https://wiki.gnucash.org/wiki/Flatpak#Using_Command_Line_Tools
yields:
GnuCash 4.14
Build ID: Flathub 4.14

so it looks as though some version information in the Flatpak repository for GC hasn't been updated properly.

**Comment by jralls** [comment]
I'm in the middle of a double release for 4.14 and 5.0, so in a couple more hours you can do it again and get 5.0. 

I have no idea what KDE discover does, perhaps they have caches that haven't or maybe hadn't caught up.
