### ISSUE TITLE
Help does not work on Mint 18

### ISSUE THREAD

**Issue by cleanman2** [flathub/org.gnucash.GnuCash#7]
I installed GnuCash using the flatpak in Software Manager yesterday. It installed and ran, but when I clicked on a help topic I received an error message that indicated some files were missing. Looking at the regular package on Software Manager there is a separate docs package. When I installed the normal way help worked as expected.  Maybe the docs package needs to be included in the flatpak.

Regards,  Jim

**Comment by gjanssens** [comment]
Yes. I am experimenting with adding the documentation in our nightly flatpak builds but there are still a few issues to solve.
