### ISSUE TITLE
Update Finance::Quote

### ISSUE THREAD

**Issue by idunno101** [flathub/org.gnucash.GnuCash#72]
Could you please update Finance::Quote to 1.55? (or 1.56 since that's the most recent)

It would fix [this issue](https://bugs.gnucash.org/show_bug.cgi?id=798896) that I'm experiencing. Thank you.

**Comment by jralls** [comment]
We'll update F::Q for the next release, [due at the end of the month](https://wiki.gnucash.org/wiki/Release_Schedule). Issues and especially pull requests should be posted to the [parent repository](https://github.com/gnucash/gnucash-on-flatpak).
