### ISSUE TITLE
Non-ASCII characters in reports printed as ???

### ISSUE THREAD

**Issue by pabl0** [flathub/org.gnucash.GnuCash#80]
Subject: Package GnuCash 5.5 (7be1b91a)
Date: 2023-12-17 22:14:57 +0

Characters like Finnish ä and ö are rendered as ?? on all reports:

![image](https://github.com/flathub/org.gnucash.GnuCash/assets/2339734/b4074133-4701-4eb3-837f-272f8976f6d7)

(Should be Pysyvät vastaavat, Aineelliset hyödykkeet, etc.)

UTF-8 characters work fine everywhere else except in reports. ?? appears both on PDF and HTML exports. Not sure when this issue started, since I only need reports once a year, but the year old version worked correctly. Of course the platform has been upgraded as well during these 12 months.

**Comment by jralls** [comment]
Please file a bug at https://bugs.gnucash.org and attach a sample HTML export exhibiting the problem.
