### ISSUE TITLE
Verify package?

### ISSUE THREAD

**Issue by Altonss** [flathub/org.gnucash.GnuCash#83]
See https://docs.flathub.org/docs/for-app-authors/verification for more infos on verification

**Comment by jralls** [comment]
Unfortunately that's not helpful as flathub.org doesn't recognize me as a developer: There is no developer tab when I'm logged in, nor does the [GnuCash page](https://flathub.org/apps/org.gnucash.GnuCash) have a developer settings item.

I've asked @gjanssens, who originally set up org.gnucash.GnuCash on Flathub, to see if he can do anything. 

This is tracked in [GnuCash's Bugzilla](https://bugs.gnucash.org/show_bug.cgi?id=799265) so closing this issue.

**Comment by gjanssens** [comment]
I'm afk until next week. I'll look at this when I'm back.
