### ISSUE TITLE
Please include aqbanking v6.5.6-beta

### ISSUE THREAD

**Issue by bauen1** [flathub/org.gnucash.GnuCash#85]
The 6.5.6-beta fixes an issue that breaks online banking with the "decouple TAN":

https://github.com/aqbanking/aqbanking/compare/6.5.5-beta...6.5.6-beta

It would be quite nice if you could bump the dependency up to that version.

**Comment by jralls** [comment]
It's AQBanking 6.5.8beta, and it's already in place in the [nightly builds](https://wiki.gnucash.org/wiki/Flatpak#Nightly_Test_Versions_at_gnucash.org). We'll put it in the GnuCash 5.7 release flatpak but only if Martin makes it a proper release.

**Comment by fellen** [comment]
… and Martin explained his process today on his mailing list.

**Comment by bauen1** [comment]
> … and Martin explained his process today on his mailing list.

Where ?
Because having all online banking broken is, mildly annoying.

**Comment by fellen** [comment]
> > … and Martin explained his process today on his mailing list.

As subscriber of https://mailman.aqbanking.de/listinfo/aqbanking-user you should be able to see it in https://mailman.aqbanking.de/private/aqbanking-user/
For your convenience I copy it here:
```
Ueberblick zum Entwicklungsprozess:

Hin und wieder kommt es vor, dass es groessere Veraenderungen in den Specs der verwendeten Homebanking-Protokolle gibt. Manche Veraenderungen sorgen dafuer, dass Homebanking ohne groessere Aenderungen nicht weiter funktioniert.

In solchen Faellen sind mal kleinere, mal groessere Code-Aenderungen notwendig. Die muss dann erst mal jemand herausfinden und dann in AqBanking einbauen. Fuer ein freies Open-Source-Projekt sind wir da schon recht gut aufgestellt.

Diese Aenderungen muessen dann aber auch getestet werden, um sagen zu koennen, ob sie funktionieren. Problem: Es gibt keinen offiziellen Test-Server, d.h. wir muessen das immer live gegen echte Banken testen. Auch das funktioniert bei uns ganz gut, zumindest hat sich bisher noch keine Bank beschwert.

Aber wir koennen das nur gegen Banken testen, bei denen wir selbst Konten haben. Wenn also meine Banken bestimmte neue Features noch nicht verwenden oder anbieten, muss ich auf Rueckmeldung von anderen Usern warten, bei denen das schon getestet werden kann oder muss.

Diesen Usern muessen wir ja irgendwas zur Verfuegung stellen, womit sie arbeiten koennen. Nicht jeder kann oder will aus dem GIT arbeiten, daher bieten wir tar.gz-Pakete an. Das sind dann die BETA-Pakete. Da kann es also durchaus sein, dass es noch nicht ganz so funktioniert, wie geplant. Darueber bekomme ich dann wieder Bugreports oder andere Rueckmeldungen, passe den Code wieder an und gebe eine neue BETA-Version heraus. Wenn das mit den Rueckmeldungen gut laeuft und ich gute Logs bekomme, kann das auch mal schnell gehen (also manchmal mehrere BETAs an einem Tag, wenn ich mal frei habe).

Wenn eine BETA schon aelter ist, ist es in der Regel so, dass bisher keine weiteren Aenderungen noetig waren, es also so funktioniert. Oder es ist hoffnungslos (die andere Moeglichkeit, ist hier aber nicht der Fall). Dann kannst Du die nehmen. Ich selbst verwende die Betas selbst immer gleich sofort (kann aber notfalls selber was dran aendern).

Wenn ich genug Rueckmeldungen habe, gebe ich in der Regel einen non-Beta heraus. In diesem Fall muss ich noch Build-Probleme in Gwen beheben (von der neuesten Version haengen ja AqBankings letzte Betas ab.

Das ganze waere natuerlich einfacher, wenn wir von den Banken unterstuetzt wuerden - frueher hatten wir mal Zugriff auf einen Test-Server einer Bank (bei der GAD, glaube ich), aber unserer damaliger Ansprechpartner reagiert in den letzten Jahren sinngemaess nur noch mit "ich schaue mal, was sich machen laesst" und laesst dann nix mehr von sich hoeren.

<rant>
Insgesamt scheinen die Banken aber ohnehin kein Interesse mehr an HBCI/FinTS zu haben, die wollen einem lieber ihre Apps aufdraengen. Wir waren vor 10-15 Jahren mal soweit voraus - das erste Land der Welt, mit einem offenen und fuer fast alle Banken einheitlichen Homebanking-Standard.

Frueher ware es ein absolutes No-Go, z.B. TAN ueber das gleiche Handy zu empfangen, auf dem man Banking macht. Heute draengen die Banken einem diese Handy-Apps geradzu auf. Daher rechne ich damit, dass die Banken FinTS irgendwann ganz einstellen. Dann koennen wir wieder wie vor 20 Jahren CSV-Dateien herunterladen und importieren.

<serious rant>
Aber es fuegt sich ganz gut in die heutige Zeit. In DE klappt ja fast nix mehr, und wenn etwas funktioniert, werden es schon irgendwelche Einzelinteressen oder Investoren kaputt kriegen 😉
</serious rant>

</rant>


Gruss
Martin 
```

> Where ? Because having all online banking broken is, mildly annoying.

Not `all online banking`. IIRC the last changes fixed an issue of some Sparkasse methods, one association beneath others using FinTS. And AqBanking has also more modules.

**Comment by fellen** [comment]
> It's AQBanking 6.5.8beta, and it's already in place in the [nightly builds](https://wiki.gnucash.org/wiki/Flatpak#Nightly_Test_Versions_at_gnucash.org). We'll put it in the GnuCash 5.7 release flatpak but only if Martin makes it a proper release.

FYI since 2024-06-02 there is [aqbanking-6.5.11beta.tar.gz](https://www.aquamaniac.de/rdm/attachments/524/aqbanking-6.5.11beta.tar.gz). Details in the aqbanking-user thread `Probleme bei PushTAN `

**Comment by jralls** [comment]
We've got a release in a week and the latest non-beta AQBanking is 6.5.4 from last March, which apparently is broken for a lot of users. The nightlies have 6.5.8beta and nobody has complained in a way visible to me. @fellen has anyone complained on gnucash-de? Should we break the rules a bit and put 6.5.8beta in the release?

**Comment by fellen** [comment]
> We've got a release in a week and the latest non-beta AQBanking is 6.5.4 from last March, which apparently is broken for a lot of users. The nightlies have 6.5.8beta and nobody has complained in a way visible to me. @fellen has anyone complained on gnucash-de? Should we break the rules a bit and put 6.5.8beta in the release?

https://lists.gnucash.org/pipermail/gnucash-de/2024-April/013181.html explains, why Sparkasse clients, allegedly our biggest user group,  require 6.5.8beta.
So, yes, we should weaken the rule for aqbanking.

Others report problems with 6.5.8beta:
- https://lists.gnucash.org/pipermail/gnucash-de/2024-April/013159.html ff.
- https://lists.gnucash.org/pipermail/gnucash-de/2024-May/013203.html ff.

Martin thinks he fixed them in [aqbanking-6.5.11beta](https://www.aquamaniac.de/rdm/attachments/524/aqbanking-6.5.11beta.tar.gz) as he had before missed one detail of the specs. On aqbanking-user he got feedback that it fixed the issues.

So IMHO we should build the remaining nightlies before the release with 6.5.11beta and release that if no complains arrive.

**Comment by jralls** [comment]
OK, I pushed a commit to build 6.5.11beta in the flatpak and Windows for tonight's nightly. I didn't have time to test it so fingers crossed. Please check the builds later this morning and if they're OK tell the folks on gnucash-de to test it as thoroughly as they can.

**Comment by fellen** [comment]
On the way:
[Nightlies mit AqBanking 6.5.11beta; war: Online Banking Sparkasse - No valid iTAN method found](https://lists.gnucash.org/pipermail/gnucash-de/2024-June/013218.html)

**Comment by jralls** [comment]
Neither nightly built. I got the tarball URI wrong in Windows but there's no log for flatpak. Testing locally I find that aqb6.5.11beta requires gwen5.11.2beta. Local test builds in progress.

**Comment by fellen** [comment]
Oh, it seems I was still in my after-midnight-mode (decrementing my clocks date to get that of code) when I checked the directories this morning, sorry.

**Comment by jralls** [comment]
No matter, nothing you could have done about it anyway. I think it's fixed now, building successfully for me on both Windows and Flatpak.

**Comment by jralls** [comment]
Fixed indeed, both nightlies completed successfully.

**Comment by fellen** [comment]
Martin's release plans:
https://lists.gnucash.org/pipermail/gnucash-de/2024-June/013221.html

**Comment by jralls** [comment]
That's unfortunate. I guess we release 5.7 with AQB 6.5.4 and put the nightlies at 6.5.12beta on Monday.

**Comment by fellen** [comment]
As said before AQB 6.5.4 will make online banking unusable for many Sparkasse clients.
And we got no complains on gnucash-de, but also no other responses.

**Comment by jralls** [comment]
> As said before AQB 6.5.4 will make online banking unusable for many Sparkasse clients.

That seems not to have changed, otherwise Martin would be releasing 6.5.12 instead of 6.5.12beta. Those for whom it's working can continue to use the nightly builds and so continue to help Martin get to an eventual official release.

> And we got no complains on gnucash-de, but also no other responses.

[Not so.](https://bugs.gnucash.org/show_bug.cgi?id=799302)

**Comment by bauen1** [comment]
> > > … and Martin explained his process today on his mailing list.
> 
> As subscriber of https://mailman.aqbanking.de/listinfo/aqbanking-user you should be able to see it in https://mailman.aqbanking.de/private/aqbanking-user/ For your convenience I copy it here:

Thanks, I'm not subscribed to that list, so I don't have access to it. 

> <rant>
> Insgesamt scheinen die Banken aber ohnehin kein Interesse mehr an HBCI/FinTS zu haben, die wollen einem lieber ihre Apps aufdraengen. Wir waren vor 10-15 Jahren mal soweit voraus - das erste Land der Welt, mit einem offenen und fuer fast alle Banken einheitlichen Homebanking-Standard.
> 
> Frueher ware es ein absolutes No-Go, z.B. TAN ueber das gleiche Handy zu empfangen, auf dem man Banking macht. Heute draengen die Banken einem diese Handy-Apps geradzu auf. Daher rechne ich damit, dass die Banken FinTS irgendwann ganz einstellen. Dann koennen wir wieder wie vor 20 Jahren CSV-Dateien herunterladen und importieren.
>  [...]

And they don't have a problem with installing their online banking app and their 2FA app on the same device, somewhat defeating their purpose, my bank actually added code to make the redirection between the apps work smoother ...

> > Where ? Because having all online banking broken is, mildly annoying.
> 
> Not `all online banking`. IIRC the last changes fixed an issue of some Sparkasse methods, one association beneath others using FinTS. And AqBanking has also more modules.

Yes, that was an overaggrevated by me, since the only online banking that "works" in GnuCash for me personally is PayPal right now (And there only receiving transactions is possible ...)
