### ISSUE TITLE
3.0 released

### ISSUE THREAD

**Issue by TingPing** [flathub/org.gnucash.GnuCash#9]
https://lists.gnucash.org/pipermail/gnucash-user/2018-April/075866.html

Big release with things like the gtk3/webkit2 migration.

**Comment by barthalion** [comment]
Running a local test build now.

**Comment by matejak** [comment]
Cool that there is a PR #10 , when can we expect it to hit the repo?

**Comment by barthalion** [comment]
When someone has time to figure out the build failure of one of the dependencies.

**Comment by eszlari** [comment]
I guess this issue can be closed.
